dependent_repositories:
- name: kogito-runtimes
  branch: 3265.2.x
- name: kogito-apps
  branch: 3265.2.x
- name: kogito-examples
  branch: 3265.2.x
- name: kogito-images
  branch: 3265.2.x
- name: kogito-operator
  branch: 3265.2.x
- name: optaplanner
  branch: 3272.2.x
