dependent_repositories:
- name: kogito-runtimes
  branch: 25.999.x
- name: kogito-apps
  branch: 25.999.x
- name: kogito-examples
  branch: 25.999.x
- name: kogito-images
  branch: 25.999.x
- name: kogito-operator
  branch: 25.999.x
- name: optaplanner
  branch: 25.1006.x
