dependent_repositories:
- name: kogito-runtimes
  branch: 102.0.x
- name: kogito-apps
  branch: 102.0.x
- name: kogito-examples
  branch: 102.0.x
- name: kogito-images
  branch: 102.0.x
- name: kogito-operator
  branch: 102.0.x
- name: optaplanner
  branch: 100.10.x
- name: rhpam-kogito-operator
  branch: 102.0.x
