dependent_repositories:
- name: kogito-runtimes
  branch: 250.1.x
- name: kogito-apps
  branch: 250.1.x
- name: kogito-examples
  branch: 250.1.x
- name: kogito-images
  branch: 250.1.x
- name: kogito-operator
  branch: 250.1.x
- name: rhpam-kogito-operator
  branch: 250.1.x
- name: optaplanner
  branch: 257.1.x
