dependent_repositories:
- name: kogito-runtimes
  branch: 1563.2.x
- name: kogito-apps
  branch: 1563.2.x
- name: kogito-examples
  branch: 1563.2.x
- name: kogito-images
  branch: 1563.2.x
- name: kogito-operator
  branch: 1563.2.x
- name: optaplanner
  branch: 1570.2.x
