dependent_repositories:
- name: kogito-runtimes
  branch: 100.0.x
- name: kogito-apps
  branch: 100.0.x
- name: kogito-examples
  branch: 100.0.x
- name: kogito-images
  branch: 100.0.x
- name: kogito-operator
  branch: 100.0.x
- name: optaplanner
  branch: 100.7.x
- rhpam-kogito-operator
