git:
  branches:
  - master
  - 1.5.x
  - 1.8.x
  author:
    name: radtriste
    credentials_id: radtriste
    token_credentials_id: radtriste-gh-token
  bot_author:
    name: radtriste-bot-account
    credentials_id: radtriste-bot
  main_branch:
    default: master
maven:
  settings_file_id: 2bd418aa-56fa-4403-9232-8c77a50fc528
  nexus:
    release_url: https://repository.stage.jboss.org/nexus
    release_repository: jboss-releases-repository
    staging_profile_url: https://repository.stage.jboss.org/nexus/content/groups/kogito-public/
    staging_profile_id: 2161b7b8da0080
    build_promotion_profile_id: 1966c60aff37d
  artifacts_repository: http://nexus3-tradisso-nexus.apps.kogito-cloud.hosted.psi.rdu2.redhat.com/repository/kogito-test/
  #artifacts_repository: ''
  pr_checks:
    repository:
      url: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/repositories/kogito-runtimes-pr-full-testing/
      creds_id: unpacks-zip-on-qa-nexus
cloud:
  image:
    registry_credentials_nightly: tradisso_registry_token
    registry_credentials_release: tradisso_registry_token
    registry: quay.io
    namespace: tradisso
    latest_git_branch: master
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO_PERSO
quarkus:
  lts_version: '1.11'
disable:
  triggers: true
